using Serenity.Navigation;
using MyPages = wheystore.SanPhamDB.Pages;

[assembly: NavigationLink(1000, "SanPhamDB/San Pham", typeof(MyPages.SanPhamPage), icon: null)]
[assembly: NavigationLink(1001, "SanPhamDB/Danh Muc San Pham", typeof(MyPages.DanhMucSanPhamPage), icon: null)]
[assembly: NavigationLink(1002, "SanPhamDB/Nha Cung Cap", typeof(MyPages.NhaCungCapPage), icon: null)]
[assembly: NavigationLink(1004, "SanPhamDB/Khach Hang", typeof(MyPages.KhachHangPage), icon: null)]
[assembly: NavigationLink(1005, "SanPhamDB/Shippers", typeof(MyPages.ShippersPage), icon: null)]
[assembly: NavigationLink(1003, "SanPhamDB/Thuong Hieu", typeof(MyPages.ThuongHieuPage), icon: null)]
[assembly: NavigationLink(1018, "SanPhamDB/Review", typeof(MyPages.ReviewPage), icon: null)]
[assembly: NavigationLink(1007, "SanPhamDB/Danh Muc Tin Tuc", typeof(MyPages.DanhMucTinTucPage), icon: null)]
[assembly: NavigationLink(1006, "SanPhamDB/Tin Tuc", typeof(MyPages.TinTucPage), icon: null)]
[assembly: NavigationLink(1008, "SanPhamDB/Don Hang", typeof(MyPages.DonHangPage), icon: null)]
[assembly: NavigationLink(1009, "SanPhamDB/Chi Tiet Don Hang", typeof(MyPages.ChiTietDonHangPage), icon: null)]
[assembly: NavigationLink(1010, "SanPhamDB/Gio Hang", typeof(MyPages.GioHangPage), icon: null)]
[assembly: NavigationLink(1011, "SanPhamDB/Qua Tang", typeof(MyPages.QuaTangPage), icon: null)]
[assembly: NavigationLink(1012, "SanPhamDB/San Pham Bien The", typeof(MyPages.SanPhamBienThePage), icon: null)]
[assembly: NavigationLink(1013, "SanPhamDB/San Pham Chi Tiet", typeof(MyPages.SanPhamChiTietPage), icon: null)]
[assembly: NavigationLink(1014, "SanPhamDB/San Pham Huong Vi", typeof(MyPages.SanPhamHuongViPage), icon: null)]
[assembly: NavigationLink(1015, "SanPhamDB/San Pham Noi Dung", typeof(MyPages.SanPhamNoiDungPage), icon: null)]
[assembly: NavigationLink(1016, "SanPhamDB/San Pham Qua Tang", typeof(MyPages.SanPhamQuaTangPage), icon: null)]
[assembly: NavigationLink(1019, "SanPhamDB/Ma Giam Gia", typeof(MyPages.MaGiamGiaPage), icon: null)]
[assembly: NavigationLink(1017, "SanPhamDB/San Pham Lien Quan", typeof(MyPages.SanPhamLienQuanPage), icon: null)]
[assembly: NavigationLink(int.MaxValue, "SanPhamDB/San Pham Huong Vi Link", typeof(MyPages.SanPhamHuongViLinkPage), icon: null)]